### ISSUE TITLE
请求对三代游戏的画图进行适配

### ISSUE THREAD

**Issue by lux032** [tyangdev/SplaTu#1]

**Comment by Giresharu** [comment]
https://github.com/tarxf/Splatoon-3-Post-Printer/ 3代可以使用这个项目，不过要自己按照说明编译

**Comment by tyangdev** [comment]
> https://github.com/tarxf/Splatoon-3-Post-Printer/ 3代可以使用这个项目，不过要自己按照说明编译

感谢各位建议，最近在忙很多三次元的事情，等空下来了我去看看

**Comment by tyangdev** [comment]
图片生成部分已经更新，另外更新了文件夹结构以适应新版本的打印插件
